### ISSUE TITLE
0.7.0 release target

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#168]
This issue is to document the set of features/bug fixes for the next (v0.7) HDF Compass Release
- [ ] Tree View for object hierarchy - #66
- [ ] Fix OpenDAP plugin: #60
- [ ] User Guide - #76
- [ ] Better support for attribute display - #72
- [ ] Better support for viewing HDF5 images - #23 
- [ ] External/Soft links support - #77
- [x] Clipboard Support - #21 #175 
- [ ] Improve display of linked datatypes - #25 
- [ ] Improve display of committed types - #75

Excluded from this list (but intended for the next release) are some items (e.g. code signing for Mac binaries) that are a HDFGroup build/deploy process and not a source code issue per se.

**Comment by jreadey** [comment]
I'd leave out #66 (Tree View) from the release target.  Implementing is not easy and I'm not entirely sold on its usefulness.

Let's add #164 (Windows installer).  I can work on this.

How about adding #132: Handle multiple plugins?  

I created an issue #183 to use one top-level window.  Any supporters of that approach?

**Comment by giumas** [comment]
> I'd leave out #66 (Tree View) from the release target. Implementing is not easy and I'm not entirely sold on its usefulness.

@jreadey : can you explain what was wrong with the work done in https://github.com/HDFGroup/hdf-compass/pull/100 before the addition of the graph idea (that I agree is not so useful)?

**Comment by ghost** [comment]
> I created an issue #183 to use one top-level window. Any supporters of that approach?

Me.

I'd also suggest easier access to HDF5 attributes. Something like clicking on _HDF5 attributes_. The current _Open as HDF5 attributes_ never seemed natural to me.

**Comment by jreadey** [comment]
@hyoklee did a bunch of work on implementing the tree view last year, but I don't think it was ready for prime time.  @hyoklee how much more work do you think it would take to complete?

**Comment by giumas** [comment]
@hyoklee From my understanding, wx provides a 'native' way to display a tree, not a graph. This is the reason of the slowing down of the ticket resolution. I remember that I tested the tree-only part and it was working well.

**Comment by ghisvail** [comment]
Just to let you guys know that Debian will soon freeze for its upcoming stable release, so for now we are aiming for providing version `0.6.0` of `hdf-compass`. `hydroffice.bag` is now available in the archive, and `cartopy` is ready. I don't know what is the status with `pydap` but it looks like it is still at a stand-still, so this plugin won't be functional I am afraid.
